default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kylej
  password: YaeMikoSimp#1
  host: localhost
  port: 5433                   

development:
  <<: *default
  database: yae_publishing_house_development

test:
  <<: *default
  database: yae_publishing_house_test

production:
  primary: &primary_production
    <<: *default
    database: yae_publishing_house_production
    username: yae_publishing_house
    password: <%= ENV["YAE_PUBLISHING_HOUSE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: yae_publishing_house_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: yae_publishing_house_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: yae_publishing_house_production_cable
    migrations_paths: db/cable_migrate